(function(){
const API_BASE = (['8080','80','5500','5173'].includes(location.port)) ? 'http://localhost:3000' : '';
const money = v => 'R$ ' + Number(v || 0).toFixed(2).replace('.', ',');
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let products=[];
function requireAdmin(){ if(localStorage.getItem('usuario')!=='admin' && !location.pathname.endsWith('/adm_login.html')) location.href='../adm_login.html'; }
async function api(path, opts){ const res=await fetch(API_BASE+path, opts); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error||'Erro na requisição'); return data; }
function setStatus(msg,type=''){ const el=document.getElementById('formStatus')||document.getElementById('dbStatus'); if(el){el.textContent=msg; el.className='status '+type;} }
async function loadDashboard(){ if(!document.getElementById('countProducts')) return; try{ const [p,u,h]=await Promise.all([api('/api/products'),api('/api/users'),api('/api/health')]); document.getElementById('countProducts').textContent=p.length; document.getElementById('countUsers').textContent=u.length; document.getElementById('countPromos').textContent=p.filter(x=>Number(x.oldPrice)>Number(x.price)).length; const db=document.getElementById('dbStatus'); if(db){db.textContent=h.dbConnected?'Banco MySQL conectado.':'Servidor OK, usando JSON/fallback.'; db.className='status '+(h.dbConnected?'ok':'');} }catch(e){ setStatus('Erro ao carregar dashboard: '+e.message,'err'); } }
function fillForm(p){ const refs=getFormRefs(); refs.produtoId.value=p.id; refs.title.value=p.title||''; refs.brand.value=p.brand||''; refs.price.value=p.price||''; refs.oldPrice.value=p.oldPrice||''; refs.image.value=p.image||''; refs.description.value=p.description||''; refs.specs.value=Array.isArray(p.specs)?p.specs.join('\n'):(p.specs||''); refs.saveBtn.textContent='Salvar alterações'; window.scrollTo({top:0,behavior:'smooth'}); }
function getFormRefs(){ return { produtoId:document.getElementById('produtoId'), title:document.getElementById('title'), brand:document.getElementById('brand'), price:document.getElementById('price'), oldPrice:document.getElementById('oldPrice'), image:document.getElementById('image'), description:document.getElementById('description'), specs:document.getElementById('specs'), saveBtn:document.getElementById('saveBtn'), cancelBtn:document.getElementById('cancelBtn') }; }
function clearForm(){ const form=document.getElementById('produtoForm'); const refs=getFormRefs(); form?.reset(); if(refs.produtoId) refs.produtoId.value=''; if(refs.saveBtn) refs.saveBtn.textContent='Salvar Produto'; }
function renderProducts(list=products){ const tbody=document.getElementById('produtosTbody'); if(!tbody) return; tbody.innerHTML=list.length?list.map(p=>`<tr><td>${p.id}</td><td>${esc(p.title)}</td><td>${esc(p.brand||'-')}</td><td>${money(p.price)}</td><td><div class="admin-actions"><button class="btn-secondary btn-small" data-edit="${p.id}">Editar</button><button class="btn-danger btn-small" data-del="${p.id}">Excluir</button></div></td></tr>`).join(''):'<tr><td colspan="5">Nenhum produto cadastrado.</td></tr>'; tbody.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>fillForm(products.find(p=>String(p.id)===String(b.dataset.edit)))); tbody.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{ if(!confirm('Excluir este produto?'))return; try{await api('/api/products/'+b.dataset.del,{method:'DELETE'}); await loadProducts(); setStatus('Produto excluído.','ok');}catch(e){setStatus(e.message,'err');} }); }
async function loadProducts(){ if(!document.getElementById('produtosTbody')) return; try{ products=await api('/api/products'); renderProducts(); }catch(e){ setStatus('Erro ao carregar produtos: '+e.message,'err'); } }
function bindProductForm(){ const form=document.getElementById('produtoForm'); if(!form) return; const refs=getFormRefs(); refs.cancelBtn.onclick=clearForm; form.addEventListener('submit',async e=>{ e.preventDefault(); const refs=getFormRefs(); const id=refs.produtoId.value; const payload={title:refs.title.value,brand:refs.brand.value,price:refs.price.value,oldPrice:refs.oldPrice.value,image:refs.image.value,description:refs.description.value,specs:refs.specs.value}; try{ await api('/api/products'+(id?'/'+id:''),{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); clearForm(); await loadProducts(); setStatus(id?'Produto atualizado e salvo. Veja no index pelo botão azul.':'Produto cadastrado. Veja no index pelo botão azul.','ok'); }catch(e){ setStatus(e.message,'err'); } }); document.getElementById('adminSearch')?.addEventListener('input',e=>{ const q=e.target.value.toLowerCase(); renderProducts(products.filter(p=>String(p.title+' '+(p.brand||'')).toLowerCase().includes(q))); }); }
async function loadUsers(){ const tbody=document.getElementById('usersTbody'); if(!tbody) return; try{ const users=await api('/api/users'); tbody.innerHTML=users.map(u=>`<tr><td>${u.id}</td><td>${esc(u.name||u.nome)}</td><td>${esc(u.email)}</td><td>${esc(u.tipo||'cliente')}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum usuário.</td></tr>'; }catch(e){ tbody.innerHTML='<tr><td colspan="4">Erro ao carregar usuários.</td></tr>'; } }
async function loadReports(){ const box=document.getElementById('relatorioResumo'); if(!box) return; try{ const [p,u]=await Promise.all([api('/api/products'),api('/api/users')]); const promos=p.filter(x=>Number(x.oldPrice)>Number(x.price)); box.innerHTML=`<div class="box"><h2>Produtos</h2><span>${p.length}</span></div><div class="box"><h2>Usuários</h2><span>${u.length}</span></div><div class="box"><h2>Promoções</h2><span>${promos.length}</span></div>`; }catch(e){ box.innerHTML='<div class="card">Erro ao carregar relatórios.</div>'; } }
document.addEventListener('DOMContentLoaded',()=>{ requireAdmin(); document.getElementById('adminLogout')?.addEventListener('click',e=>{e.preventDefault();localStorage.removeItem('usuario');localStorage.removeItem('usuario_email');location.href='../adm_login.html';}); loadDashboard(); bindProductForm(); loadProducts(); loadUsers(); loadReports(); });
})();
