(function(){
const money = v => 'R$ ' + Number(v || 0).toFixed(2).replace('.', ',');
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function getCart(){ return JSON.parse(localStorage.getItem('carrinho') || '[]'); }
function setCart(items){ localStorage.setItem('carrinho', JSON.stringify(items)); }
function render(){ const box=document.getElementById('cartItems'); if(!box) return; const items=getCart(); if(!items.length){ box.innerHTML='<div class="empty">Seu carrinho está vazio. <br><br><a class="btn-primary" href="index.html">Ver promoções</a></div>'; updateTotal(); return; } box.innerHTML=''; items.forEach((item,idx)=>{ const el=document.createElement('div'); el.className='item'; el.innerHTML=`<img src="${esc(item.image||item.img||'https://picsum.photos/seed/cart/300/300')}" alt="${esc(item.title||item.titulo)}"><div><h3>${esc(item.title||item.titulo)}</h3><p class="preco">${money(item.price || parsePrice(item.preco))}</p></div><input class="quantidade" type="number" min="1" value="${Number(item.quantidade||1)}"><div class="acoes"><button class="btn-secondary btn-small ver">Ver Pedido</button><button class="remover btn-small">Remover</button></div>`; el.querySelector('.quantidade').onchange=e=>{items[idx].quantidade=Math.max(1,Number(e.target.value||1));setCart(items);render();}; el.querySelector('.remover').onclick=()=>{items.splice(idx,1);setCart(items);render();}; el.querySelector('.ver').onclick=()=>openPedido([items[idx]]); box.appendChild(el); }); updateTotal(); }
function parsePrice(text){ if(typeof text==='number') return text; return Number(String(text||'0').replace(/[R$\s.]/g,'').replace(',','.'))||0; }
function updateTotal(){ const total=getCart().reduce((s,i)=>s+(Number(i.price||parsePrice(i.preco))*Number(i.quantidade||1)),0); document.getElementById('subtotal').textContent=money(total); document.getElementById('total').textContent=money(total); }
function openPedido(items){ const overlay=document.getElementById('pedidoOverlay'); const modal=document.getElementById('pedidoModal'); const content=document.getElementById('pedidoContent'); const total=items.reduce((s,i)=>s+(Number(i.price||parsePrice(i.preco))*Number(i.quantidade||1)),0); content.innerHTML=items.map(i=>`<div style="display:flex;gap:12px;align-items:center;margin-bottom:12px"><img src="${esc(i.image||i.img||'https://picsum.photos/seed/cart/300/300')}" style="width:74px;height:74px;object-fit:cover;border-radius:12px"><div><strong>${esc(i.title||i.titulo)}</strong><p class="muted">Qtd: ${Number(i.quantidade||1)} — ${money(i.price||parsePrice(i.preco))}</p></div></div>`).join('')+`<hr><p><strong>Total: ${money(total)}</strong></p>`; overlay.classList.add('show'); modal.classList.add('show'); }
function closePedido(){ document.getElementById('pedidoOverlay')?.classList.remove('show'); document.getElementById('pedidoModal')?.classList.remove('show'); }
document.addEventListener('DOMContentLoaded',()=>{ render(); document.getElementById('btnFinalizar')?.addEventListener('click',()=>{ const items=getCart(); if(!items.length){alert('Seu carrinho está vazio.');return} openPedido(items); }); document.getElementById('btnLimpar')?.addEventListener('click',()=>{ if(confirm('Limpar carrinho?')){setCart([]);render();} }); document.getElementById('fecharPedido')?.addEventListener('click',closePedido); document.getElementById('pedidoOverlay')?.addEventListener('click',closePedido); document.getElementById('confirmarCompra')?.addEventListener('click',()=>{alert('Pedido confirmado!');setCart([]);closePedido();render();}); });
})();
