(function(){
const API_BASE = window.API_BASE || ((['8080','80','5500','5173'].includes(location.port)) ? 'http://localhost:3000' : '');
const money = window.money || (v => 'R$ ' + Number(v || 0).toFixed(2).replace('.', ','));
const esc = window.escapeHTML || (v => String(v ?? ''));
let allProducts = [];
function cart(){ return JSON.parse(localStorage.getItem('carrinho') || '[]'); }
function saveCart(items){ localStorage.setItem('carrinho', JSON.stringify(items)); }
function addToCart(product, redirect=false){ const items = cart(); const found = items.find(i => String(i.id) === String(product.id)); if(found) found.quantidade = Number(found.quantidade || 1) + 1; else items.push({ id: product.id, title: product.title, price: Number(product.price||0), image: product.image, quantidade: 1 }); saveCart(items); if(redirect) location.href='carrinho.html'; else alert('Produto adicionado ao carrinho!'); }
function render(products){ const grid = document.getElementById('productGrid'); if(!grid) return; if(!products.length){ grid.innerHTML = '<div class="card empty">Nenhum produto encontrado.</div>'; return; } grid.innerHTML=''; products.forEach(p=>{ const card=document.createElement('article'); card.className='card-prod'; card.innerHTML=`<img src="${esc(p.image || 'https://picsum.photos/seed/promo/600/400')}" alt="${esc(p.title)}"><div class="body"><span class="tag">Promoção</span><h3>${esc(p.title)}</h3><p class="muted">${esc(p.brand || 'Oferta especial')}</p><p><span class="preco">${money(p.price)}</span>${p.oldPrice ? `<span class="oldpreco">${money(p.oldPrice)}</span>`:''}</p><div class="card-actions"><button class="btn-primary btn-comprar">Comprar</button><button class="btn-secondary btn-add">Adicionar</button><button class="btn-secondary btn-info">Ver detalhes</button></div></div>`; card.querySelector('.btn-add').onclick=()=>addToCart(p,false); card.querySelector('.btn-comprar').onclick=()=>addToCart(p,true); card.querySelector('.btn-info').onclick=()=>showInfo(p); grid.appendChild(card); }); }
function showInfo(p){ const overlay=document.getElementById('infoOverlay'); const modal=document.getElementById('infoModal'); const title=document.getElementById('infoTitle'); const content=document.getElementById('infoContent'); if(title) title.textContent=p.title; if(content) content.innerHTML=`<img src="${esc(p.image || 'https://picsum.photos/seed/promo/600/400')}" style="width:100%;max-height:260px;object-fit:cover;border-radius:16px;margin-bottom:14px"><p><strong>Marca:</strong> ${esc(p.brand || '-')}</p><p><strong>Preço:</strong> ${money(p.price)} ${p.oldPrice ? `<span class="oldpreco">${money(p.oldPrice)}</span>`:''}</p><p><strong>Descrição:</strong> ${esc(p.description || 'Sem descrição cadastrada.')}</p>${Array.isArray(p.specs)&&p.specs.length?`<p><strong>Especificações:</strong></p><ul>${p.specs.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`:''}<button class="btn-primary" id="modalBuy" style="margin-top:12px">Adicionar ao carrinho</button>`; if(content) content.querySelector('#modalBuy').onclick=()=>addToCart(p,false); overlay?.classList.add('show'); modal?.classList.add('show'); }
function closeInfo(){ document.getElementById('infoOverlay')?.classList.remove('show'); document.getElementById('infoModal')?.classList.remove('show'); }
async function load(){ const grid=document.getElementById('productGrid'); if(grid) grid.innerHTML='<div class="card empty">Carregando produtos...</div>'; try{ const res=await fetch(API_BASE+'/api/products'); if(!res.ok) throw new Error('Falha na API'); allProducts=await res.json(); }catch(e){ console.warn(e); allProducts=[]; } render(allProducts); }
document.addEventListener('DOMContentLoaded',()=>{ document.getElementById('infoClose')?.addEventListener('click', closeInfo); document.getElementById('infoOverlay')?.addEventListener('click', closeInfo); document.getElementById('searchInput')?.addEventListener('input', e=>{ const q=e.target.value.toLowerCase(); render(allProducts.filter(p=>String(p.title+' '+(p.brand||'')).toLowerCase().includes(q))); }); load(); });
})();
